Added parser
aleksandr-hrankin/amazon-reviews-analyzer pull request #2
Opened 2020-11-11 15:42 UTC by aleksandr-hrankin

2020-11-11 18:24 UTC, MaliukDaria commented on src/main/java/ua/antibyte/analyzer/dto/CommentDto.java
> +    private String text;
возможно лучше те поля, где цифры пометить как Long? А дату в DateTime?

2020-11-11 18:24 UTC, MaliukDaria commented on src/main/java/ua/antibyte/analyzer/service/impl/FileCsvParser.java
> +                }
ты можешь в csvParser указать  CSVFormat.DEFAULT.withFirstRecordAsHeader() и тогда оно само скипнет первую строчку, а так ты запускаешь проверку для каждой из 500 000 тисяц записей

2020-11-12 09:37 UTC, KseniiaMakarova requested changes

2020-11-12 09:37 UTC, KseniiaMakarova commented on src/main/java/ua/antibyte/analyzer/dto/CommentDto.java
> +    private String id;
```suggestion
    private Long id;
```
I think that the fields that look like Integer/Long values we can parse to Integer/Long fields
this seems not to be a problem with our source file

2020-11-12 09:37 UTC, KseniiaMakarova commented on src/main/java/ua/antibyte/analyzer/service/impl/FileCsvParser.java
> +public class FileCsvParser implements FileParser<CommentDto> {
```suggestion
public class CommentFileCsvParser implements FileCsvParser<CommentDto> {
```

2020-11-12 09:37 UTC, KseniiaMakarova commented on src/main/java/ua/antibyte/analyzer/service/impl/FileCsvParser.java
> +                }
> ты можешь в csvParser указать CSVFormat.DEFAULT.withFirstRecordAsHeader() и тогда оно само скипнет первую строчку, а так ты запускаешь проверку для каждой из 500 000 тисяц записей

good point!

2020-11-12 09:37 UTC, KseniiaMakarova commented on src/main/java/ua/antibyte/analyzer/service/impl/FileCsvParser.java
> +                if (FILE_HEADER[0].equals(csvRecord.get(FILE_HEADER[0]))) {
can we just skip the first line?
or check the first record separately, so that this check won't be repeated for all the records?

2020-11-12 09:37 UTC, KseniiaMakarova commented on src/test/resources/test_empty_file_with_header.csv
> +Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
empty line

2020-11-12 09:37 UTC, KseniiaMakarova commented on src/test/java/ua/antibyte/analyzer/service/impl/ReadingCsvServiceImplTest.java
> +    private static FileParser<CommentDto> fileParser;
```suggestion
    private FileParser<CommentDto> fileParser;
```

2020-11-12 12:26 UTC, aleksandr-hrankin commented on src/test/java/ua/antibyte/analyzer/service/impl/ReadingCsvServiceImplTest.java
> +    private static FileParser<CommentDto> fileParser;
Я могу сделать это поле не статическим потому что оно инициализируется в статическом методе beforeAll

2020-11-12 13:01 UTC, KseniiaMakarova requested changes

2020-11-12 13:01 UTC, KseniiaMakarova commented on src/main/java/ua/antibyte/analyzer/service/impl/CommentFileCsvParser.java
> +        implements ua.antibyte.analyzer.service.FileCsvParser<CommentDto> {
can we import the class instead of writing its full name?
here and in the Test class

2020-11-12 13:49 UTC, aleksandr-hrankin commented on src/main/java/ua/antibyte/analyzer/service/impl/CommentFileCsvParser.java
> +        implements ua.antibyte.analyzer.service.FileCsvParser<CommentDto> {
ой, то уже клиника

2020-11-12 15:58 UTC, KseniiaMakarova approved these changes

2020-11-12 15:58 UTC, KseniiaMakarova commented on src/test/java/ua/antibyte/analyzer/service/impl/ReadingCsvServiceImplTest.java
> +        List<CommentDto> actual = new ua.antibyte.analyzer.service.impl.CommentFileCsvParser().parse(EMPTY_FILE);
```suggestion
        List<CommentDto> actual = new CommentFileCsvParser().parse(EMPTY_FILE);
```

2020-11-12 15:58 UTC, KseniiaMakarova commented on src/test/java/ua/antibyte/analyzer/service/impl/ReadingCsvServiceImplTest.java
> +        List<CommentDto> actual = new ua.antibyte.analyzer.service.impl.CommentFileCsvParser().parse(EMPTY_FILE_WITH_HEADER);
```suggestion
        List<CommentDto> actual = new CommentFileCsvParser().parse(EMPTY_FILE_WITH_HEADER);
```

2020-11-12 16:34 UTC, merged